### ISSUE TITLE
Make site acessable on mobile

### ISSUE THREAD

**Issue by ghost** [latentdev/JP-Project#15]

**Comment by latentdev** [comment]
site is accessible on mobile

**Comment by latentdev** [comment]
already fully scaleable

**Comment by ghost** [comment]
Is it optimized for mobile?

**Comment by latentdev** [comment]
yeah except for the temporary part that outputs the tweets. go to ld.azurewebsites.net in a mobile browser. currently though once the tweets are returned the width breaks because the div holding the tweets doesn't have a defined width.
