### ISSUE TITLE
Sentiment Analysis (SA) in R

### ISSUE THREAD

**Issue by latentdev** [latentdev/JP-Project#4]
Determine whether a tweet is positive or negative regarding the query.

**Comment by ghost** [comment]
Am working on building a generic algorithm that we could implement in any language to filter "sentiment." The rudimentary one will read in a dictionary and learn certain 'positive' and 'negative' words, with neutrals being excluded from queries.

**Comment by ghost** [comment]
Would anyone like to try their hand at another form of twitter analysis, such as correlated data?
